site_name: Vini Data API Documentation
repo_url: https://github.com/marcosnataqs/vini_data_api

theme: material

plugins:
 - mkdocstrings

markdown_extensions:
 - pymdownx.emoji
 - pymdownx.tasklist
 - pymdownx.mark
 - pymdownx.tilde
 - pymdownx.highlight
 
nav:
 - Overview: index.md
 - Projeto: projeto.md 
 - Requisitos: requisitos.md
 - Arquitetura: arquitetura.md
 - Documentação da API: API.md
 - Checklist dos objetivos do projeto: checklist.md
